name: Build and publish

on:
  pull_request:
    branches: ["main"]
    types: [closed]

env:
  GH_REGISTRY: ghcr.io/gustheprogrammer
  IMAGE_NAME: chrona-app
  NEXT_PUBLIC_API_URL: "https://chrona.me/api"

jobs:
  prepare_release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.semver.outputs.new_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required to fetch all tags

      - name: Fetch all tags
        run: git fetch --tags

      - name: Get previous tag
        id: previoustag
        run: |
          TAG=$(git tag --sort=-v:refname | head -n1)
          if [ -z "$TAG" ]; then
            TAG="0.0.0"
          fi
          echo "Previous tag: $TAG"
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Get next minor version
        id: semver
        env:
          PREVIOUS_TAG: ${{ steps.previoustag.outputs.tag }}
        run: |
          npm install -g semver
          NEW_VERSION=$(semver -i minor "$PREVIOUS_TAG")
          echo "New version: $NEW_VERSION"
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Output versions for debugging
        env:
          PREVIOUS_TAG: ${{ steps.previoustag.outputs.tag }}
          NEW_VERSION: ${{ steps.semver.outputs.new_version }}
        run: |
          echo "Previous tag: $PREVIOUS_TAG"
          echo "New version: $NEW_VERSION"

  test:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: prepare_release
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Run Jest Tests
        run: npm test

  build_and_push:
    if: github.event.pull_request.merged == true
    needs: [test, prepare_release]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Setup .env file
        run: |
          echo NEXT_PUBLIC_API_URL="${NEXT_PUBLIC_API_URL}" >> .env
        shell: bash

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.GH_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and tag image
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:${{ needs.prepare_release.outputs.new_version }} .
          docker tag ${{ env.IMAGE_NAME }}:${{ needs.prepare_release.outputs.new_version }} ${{ env.GH_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.prepare_release.outputs.new_version }}

      - name: Push image to GitHub Container Registry
        run: |
          docker push ${{ env.GH_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.prepare_release.outputs.new_version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: '${{ needs.prepare_release.outputs.new_version }}',
              name: 'Release ${{ needs.prepare_release.outputs.new_version }}',
              body: 'Docker Image: ${{ env.GH_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.prepare_release.outputs.new_version }}'
            });
