name: Build and publish manually
on:
  pull_request:
    branches: ["main"]

env:
  DO_REGISTRY: registry.digitalocean.com/chrona-registry
  GH_REGISTRY: ghcr.io/gustheprogrammer
  IMAGE_NAME: chrona-app
  NEXT_PUBLIC_API_URL: "https://chrona.me/api"

jobs:
  prepare_release:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.semver.outputs.minor }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # required to fetch tags

      - name: Get previous tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get next minor version
        id: semver
        uses: WyriHaximus/github-action-next-semvers@v1
        with:
          version: ${{ steps.previoustag.outputs.tag }}

      - name: Create release
        uses: actions/github-script@v6
        with:
          script: |
            const releaseResponse = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: '${{ steps.semver.outputs.minor }}',
              name: 'Release ${{ steps.semver.outputs.minor }}',
              body: 'Docker Image: ghcr.io/${{ env.IMAGE_NAME }}:${{ steps.semver.outputs.minor }}'
            });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_and_push:
    needs: prepare_release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Setup .env file
        run: |
          echo NEXT_PUBLIC_API_URL="${NEXT_PUBLIC_API_URL}" >> .env
        shell: bash

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.GH_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 600

      - name: Build image
        run: docker build -t ${{ env.IMAGE_NAME }}:${{ needs.prepare_release.outputs.new_version }} .

      - name: Tag image for DO
        run: docker tag ${{ env.IMAGE_NAME }}:${{ needs.prepare_release.outputs.new_version }} ${{ env.DO_REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Tag image for GHCR
        run: docker tag ${{ env.IMAGE_NAME }}:${{ needs.prepare_release.outputs.new_version }} ${{ env.GH_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.prepare_release.outputs.new_version }}

      - name: Push image to DO Container Registry
        run: docker push ${{ env.DO_REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Push image to GHCR
        run: docker push ${{ env.GH_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.prepare_release.outputs.new_version }}
